ittory-project/ittory-client

src/api/service/WsService.ts
src/components/common/CompTest.tsx

예시 컴포넌트 이름 수정

---

package-lock.json
package.json
src/components/loginPage/LoginRedirect.tsx
src/components/sharePage/ShareLetter.tsx
src/components/writePage/Write.tsx
src/components/writePage/WriteFinishedModal.tsx
src/components/writePage/writeMainModal/WriteMainModal.tsx
src/pages/write/WritePage.tsx

한 사람만 저장하기

---

src/components/writePage/Write.tsx

이렇게 해도 모바일에서 퇴장이 안될건지?

---

src/components/connectionPage/Connection.tsx
src/components/letterboxPage/Letter.tsx
src/components/sharePage/ShareLetter.tsx
src/components/writePage/Write.tsx

Connection, Invite, 편지 종료 시 resetTime을 초기화하여 편지 시작 시 편지 시작 창 뜰 수 있게 함

새로 작성 시 resetTime 초기화

---

src/components/writePage/Write.tsx
src/components/writePage/WriteOrderPopover.tsx
src/components/writePage/writeMainModal/WriteMainModal.tsx
src/pages/write/WritePage.tsx

1. 작성 시 팝업창
- 5초 후에 사라지게
- 유저 1명이면 안뜨게
- 팝업창 관련 조건이 원래 생각했던 것보다 많아서 기존 단순 조건문 -> 수정후 useState로 관리하도록
2. 편지 작성 시작 시 카운트다운 이미지 뒤에 반투명으로 처리
3. 편지 작성 시 번호 보여주기
- 1명이면 안뜨게
- 점선 예쁘게 조금 수정함

조금 중요한 것들 위주 수정

---

src/App.css
src/index.css
src/main.tsx

모바일 위아래 여백과 기타등등 디자인

---

src/App.tsx
src/pages/receive/ReceiveLetterPage.tsx

뒤로가기 설정 테스트

---

src/pages/create/CreatePage.tsx

뒤로가기 막기 설정했던 것 전부 삭제

---

src/components/receivePage/ReceiveLetter.tsx

0번부터 시작했던 숫자설정 다시

---

src/components/sharePage/ShareLetter.tsx

화면 비율에 따라 다르게 링크 공유

---

src/components/writePage/Write.tsx
src/components/writePage/WriteLocation.tsx

모바일 화면이면 게이지를 반대로 보이게 하기

---

src/components/writePage/Write.tsx

테스트용으로 게이지만 뜨게 설정해둔 것 삭제

---

src/components/letterboxPage/Created_Modal.tsx
src/pages/connect/ConnectionPage.tsx
src/pages/create/CreatePage.tsx
src/pages/invite/InvitePage.tsx

공유링크 수정, 뒤로가기 막기 추가

---

src/components/InvitePage/Count/Count.tsx
src/components/InvitePage/HostUser.tsx
src/components/InvitePage/Member.tsx

커버 폰트 수정, 스크롤 영역 확장

---

src/components/InvitePage/Invite.tsx

대기실 코드 재수정

---

src/components/InvitePage/Invite.tsx

새로고침 삭제 버전

---

src/components/createPage/EnterInfo/LetterInfo.tsx

인풋창 움직임 수정

---

src/components/InvitePage/Count/Count.tsx
src/components/InvitePage/Loading.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx

스크롤 테스트, 로딩창 수정

---

src/components/InvitePage/Count/Count.tsx
src/components/InvitePage/Invite.tsx
src/components/createPage/CoverDeco/CoverStyle.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx
src/components/createPage/FinalLetter/CoverModal.tsx
src/components/createPage/FinalLetter/EditLetter.tsx
src/components/letterboxPage/Created_Modal.tsx
src/pages/home/HomePage.tsx
src/pages/letterbox/LetterBoxPage.tsx

페이지 뒤로가기 막기, 공유링크 수정

---

src/pages/write/WritePage.tsx

모달 항상 띄워놓게 설정해놓고 수정을 안함

---

src/components/receivePage/Receive.tsx

테스트용으로 수정하고 커밋해버렸던 것들 되돌리기

---

src/components/letterboxPage/Created_Modal.tsx

편지함 공유링크 수정

---

src/components/InvitePage/Count/Count.tsx
src/components/createPage/CoverDeco/CoverStyle.tsx
src/components/createPage/CoverDeco/FontPopup.tsx
src/components/createPage/CoverDeco/FontSelect.tsx
src/components/createPage/FinalLetter/CoverModal.tsx

폰트바 내려감 테스트

---

src/components/createPage/CoverDeco/FontPopup.tsx
src/components/createPage/FinalLetter/CoverModal.tsx

키보드 내려가면 사라지게 수정

---

src/components/createPage/CoverDeco/FontPopup.tsx

키보드 감지 재수정

---

src/components/createPage/CoverDeco/CoverStyle.tsx

키보드 코드 재수정

---

src/components/createPage/CoverDeco/CoverStyle.tsx
src/components/createPage/CoverDeco/FontPopup.tsx

높이 음수일 경우 예외 처리

---

src/components/InvitePage/HostUser.tsx
src/components/InvitePage/Member.tsx
src/components/createPage/CoverDeco/CoverStyle.tsx
src/components/createPage/CoverDeco/FontPopup.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx
src/components/createPage/FinalLetter/CoverModal.tsx
src/components/letterboxPage/Created_Modal.tsx
src/components/sharePage/ShareLetter.tsx
src/components/writePage/WriteLocation.tsx

모바일 화면 트리거 재설정

---

src/components/InvitePage/Invite.tsx
src/components/homePage/Home.tsx

랜딩 디자인 QA 반영

---

src/components/InvitePage/Loading.tsx
src/components/accountPage/DeleteReason.tsx
src/components/homePage/Home.tsx
src/components/letterboxPage/CreatedLetter.tsx
src/components/letterboxPage/Delete_letterbox.tsx
src/components/letterboxPage/LetterBox.tsx
src/components/letterboxPage/Loading.tsx
vite.config.ts

편지 삭제 오류, 탈퇴 QA 반영

---

src/components/InvitePage/Invite.tsx
src/components/createPage/CoverDeco/CoverStyle.tsx
src/components/homePage/Home.tsx

모바일 퇴장 감지 테스트, 이미지 코드 수정

---

src/components/InvitePage/HostUser.tsx
src/components/InvitePage/Invite.tsx
src/components/InvitePage/Loading.tsx
src/components/InvitePage/UserGuide.tsx
src/components/accountPage/DeleteReason.tsx
src/components/connectionPage/Connection.tsx
src/components/homePage/Header.tsx

대기실,연결페이지 오류수정, 디자인 QA 반영

---

src/components/InvitePage/Invite.tsx
src/pages/invite/InvitePage.tsx

대기실 뒤로가기 시 퇴장처리

---

src/App.css
src/components/InvitePage/Count/Count.tsx
src/components/InvitePage/Invite.tsx
src/components/InvitePage/Member.tsx
src/components/accountPage/Logout.tsx
src/components/connectionPage/Connection.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx
src/components/joinPage/Join.tsx
src/pages/home/HomePage.tsx

연결페이지 이미지로드 방식 변경/대기실 오류 수정

---

public/assets/logout.svg
public/assets/out_X.svg
src/components/accountPage/Account.tsx
src/components/accountPage/AccountDelete.tsx
src/components/accountPage/DeleteReason.tsx
src/components/accountPage/Logout.tsx
src/components/accountPage/WithdrawPopup.tsx
src/components/createPage/EnterInfo/BotttomSheet.tsx
src/components/createPage/EnterInfo/Calender.tsx
src/components/createPage/EnterInfo/CalenderView.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx
src/components/letterboxPage/Created_Modal.tsx
src/components/letterboxPage/Received_Modal.tsx
src/layout/Menu.tsx

입력창 Focus 수정/편지생성, 메뉴 디자인 QA

---

src/components/InvitePage/Count/Count.tsx
src/components/createPage/CoverDeco/CoverStyle.tsx
src/components/createPage/CoverDeco/FontPopup.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx
src/components/createPage/FinalLetter/CompleteModal.tsx
src/components/createPage/FinalLetter/EditLetter.tsx
src/components/createPage/FinalLetter/FinalInfo.tsx
src/components/createPage/FinalLetter/UserFinishModal.tsx
src/components/letterboxPage/Created_Modal.tsx
src/components/letterboxPage/Received_Modal.tsx

커서, 카운트 기능QA, 편지생성 디자인QA

---

src/components/InvitePage/Count/Count.tsx
src/components/InvitePage/HostUser.tsx
src/components/InvitePage/Invite.tsx
src/components/InvitePage/Member.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx

대기실디자인QA/스크롤영역수정

---

vite.config.ts

- [Jira Ticket: RL1M-237](https://relay-letter.atlassian.net/browse/RL1M-237)

Fix: RL1M-237 프론트엔드 개발 배포 환경 오류 화면 해소

---

.prettierrc
.prettierrc.ts
.vscode/settings.json
package-lock.json
package.json
public/assets/letterbox/chevron_left.svg
public/assets/pagination/arrow_back.svg
public/assets/pagination/arrow_next.svg
src/components/common/Pagination.tsx
src/components/letterboxPage/Letter.tsx
src/components/receivePage/ReceiveLetterContents.tsx
src/components/receivePage/ReceiveLetterCover.tsx
src/index.css
src/vite-env.d.ts
vite.config.ts

동일 파일 수정이어서 한 번에 수정했습니다 !!
- [Jira Ticket: RL1M-239](https://relay-letter.atlassian.net/browse/RL1M-239)
- [Jira Ticket: RL1M-245](https://relay-letter.atlassian.net/browse/RL1M-245)
- 커버 변경 작업은 작업이 커서 별도의 이슈로 진행할 예정입니다 !

Fix: RL1M-239 편지함 디자인 1차 QA 2건 (커버 제외)

---

src/components/letterboxPage/Letter.tsx

- [Jira Ticket: RL1M-245](https://relay-letter.atlassian.net/browse/RL1M-245)

Fix: RL1M-245 편지 내지 커버 변경

---

src/components/joinPage/Join.tsx

- [Jira Ticket: RL1M-250](https://relay-letter.atlassian.net/browse/RL1M-250)

Fix: RL1M-250 참여하기 닉네임 스페이스바 처리

---

src/components/createPage/CoverDeco/FontPopup.tsx
src/components/createPage/CoverDeco/FontSelect.tsx

- [Jira Ticket: RL1M-241](https://relay-letter.atlassian.net/browse/RL1M-241)

Fix: RL1M-241 편지 생성 - 키보드 상단 폰트 선택 영역 디자인 QA 반영

---

package-lock.json
src/api/model/LetterModel.ts
src/api/service/LetterService.ts
src/components/joinPage/Join.tsx
src/components/joinPage/JoinModal.tsx

- [Jira Ticket: RL1M-252](https://relay-letter.atlassian.net/browse/RL1M-252)

Fix: RL1M-252 참여 로직 수정

---

src/components/receivePage/Receive.tsx

- [Jira Ticket: RL1M-253](https://relay-letter.atlassian.net/browse/RL1M-253)

Fix: RL1M-253 편지 받기 - 첫 페이지 디자인 QA 1차 반영

---

src/components/receivePage/Receive.tsx
src/index.css

- [Jira Ticket: RL1M-254](https://relay-letter.atlassian.net/browse/RL1M-254)

Fix: RL1M-254 편지 받기 - 첫 페이지 확대 상태 - 디자인 QA 1차 반영

---

commitlint.config.js
lefthook.yml
package-lock.json
package.json

- [Jira Ticket: RL1M-256](https://relay-letter.atlassian.net/browse/RL1M-256)
- 반영 컨벤션: 우디가 올려주신 컨벤션
- <img src="https://github.com/user-attachments/assets/4508f5f8-b555-431b-b615-ade21685eebf" width=500 />
- 기존 도구인 Husky 설정을 제거하기 위해 `git config --unset core.hooksPath`를 먼저 실행해주셔야 합니다 :pray:
- 이후 `npm install` 부탁드립니다!

Chore: RL1M-256 git hook(lefthook)을 활용해 커밋 메시지 컨벤션 체크 자동화

---

src/api/config/AccessTokenRepository.ts
src/components/homePage/Home.tsx
src/components/joinPage/Join.tsx
src/layout/Menu.tsx

- [Jira Ticket: RL1M-263](https://relay-letter.atlassian.net/browse/RL1M-263)

Fix: RL1M-263 로그인 체크 방식을 localStorage에서 AccessTokenRepository로 변경

---

src/api/config/AccessTokenRepository.ts
src/api/config/apiInterceptor.ts

- [Jira Ticket: RL1M-264](https://relay-letter.atlassian.net/browse/RL1M-264)

Fix: RL1M-264 Refresh 과정 구현 실수로 로그인 불가, 첫 페이지 빈 화면 뜨는 버그 수정

---

src/api/config/AccessTokenRepository.ts

- [Jira Ticket: RL1M-265](https://relay-letter.atlassian.net/browse/RL1M-265)
- 오류 상황:
- 오류의 원인:

Fix: RL1M-265 최초 로그인 불가능 문제 수정 (기존 수정 작업 도중 발생한 실수가 원인)

---

src/components/InvitePage/Invite.tsx
src/components/joinPage/JoinModal.tsx

- [Jira Ticket: RL1M-258](https://relay-letter.atlassian.net/browse/RL1M-258)

Fix: 편지 참여 시 중복 참여자 오류 해결

---

src/api/service/ParticipantService.ts
src/components/InvitePage/Invite.tsx
src/components/InvitePage/Loading.tsx
src/components/createPage/FinalLetter/CompleteModal.tsx
src/components/createPage/FinalLetter/UserFinishModal.tsx

- [Jira Ticket: RL1M-272](https://relay-letter.atlassian.net/browse/RL1M-272)

Fix: 방장이 대기실 입장 시 api call 로직 수정

---

src/api/config/logout.ts
src/api/model/AuthModel.ts
src/api/service/AuthService.ts
src/layout/Menu.tsx
src/layout/TempLogin.tsx

- [Jira Ticket: RL1M-281](https://relay-letter.atlassian.net/browse/RL1M-281)
- 테스트를 위해 추가된 임시 로그인 기능을 사용할 수 있도록 버튼을 추가합니다
https://github.com/user-attachments/assets/aeb2c71b-7caf-428b-a601-40170b2b1a51

Feat: RL1M-281 임시 로그인 버튼을 사이드 메뉴에 추가

---

src/components/createPage/FinalLetter/CompleteModal.tsx
src/components/createPage/FinalLetter/FinalInfo.tsx
src/components/createPage/FinalLetter/UserFinishModal.tsx
src/components/createPage/FinalLetter/formatDeliverDate.ts

- [Jira Ticket: RL1M-287](https://relay-letter.atlassian.net/browse/RL1M-287)

Fix: RL1M-287 편지 생성 완료 모달에서 받는 날짜가 표시되지 않는 문제 수정

---

src/utils/SessionLogger/formatObjectString.ts

- [Jira Ticket: RL1M-294](https://relay-letter.atlassian.net/browse/RL1M-294)
- Safari에서 접속 시 화면 터지는 문제 수정 (undefined에 대한 `replace` 호출)
| 오류 발생                                                                                                                                   | 해결됨                                                                                                                                     |
|--------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| ![오류 발생](https://github.com/user-attachments/assets/b0d857a1-781f-4717-9f6c-de256b3883e0) | …

Fix: RL1M-294 Logger undefined 처리 개선 (formatObjectString)

---

src/components/writePage/Write.tsx
src/components/writePage/WriteLocation.tsx
src/components/writePage/writeMainList/WriteOrderList.tsx

- [Jira Ticket: RL1M-291](https://relay-letter.atlassian.net/browse/RL1M-291)

Fix: RL1M-291 위치 아이콘 오류 수정

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-295](https://relay-letter.atlassian.net/browse/RL1M-295)
- 모바일의 경우 작성 영역이 어떻게 보이는 지 테스트용 pr 입니다!

Fix: RL1M-295 편지 작성 영역 focus 수정

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-295](https://relay-letter.atlassian.net/browse/RL1M-295)

Fix: RL1M-295 편지 작성 영역 수정된 디자인 반영 (모바일 테스트 pr)

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-318](https://relay-letter.atlassian.net/browse/RL1M-318)

Fix: RL1M-318 모바일 버전 키보드 위 여백, 모바일 구분 수정

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-318](https://relay-letter.atlassian.net/browse/RL1M-318)

Fix: RL1M-318 스크롤 시 키보드 높이 계산 코드 삭제 , maxHeight 수정

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-318](https://relay-letter.atlassian.net/browse/RL1M-318)
- 모바일 테스트용 pr 입니다

Fix: RL1M-318 키보드 노출 코드 재수정

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-318](https://relay-letter.atlassian.net/browse/RL1M-318)

Fix: setVh 코드 추가

---

src/components/InvitePage/HostUser.tsx
src/components/InvitePage/Member.tsx
src/components/letterboxPage/Created_Modal.tsx
src/components/sharePage/ShareLetter.tsx
src/components/writePage/WriteLocation.tsx
src/utils/index.ts
src/utils/isMobileDevice.ts

- [Jira Ticket: RL1M-283](https://relay-letter.atlassian.net/browse/RL1M-283)

Fix: RL1M-283 좁은 width이면 PC에서 공유하기 기능 실패 개선

---

src/api/config/kakaoLogin.ts
src/api/config/setToken.ts
src/api/service/MemberService.ts
src/components/InvitePage/HostUser.tsx
src/components/accountPage/Account.tsx
src/components/accountPage/AccountDelete.tsx
src/components/createPage/Create.tsx
src/components/createPage/EnterInfo/LetterInfo.tsx
src/components/homePage/Home.tsx
src/components/joinPage/Join.tsx
src/layout/Menu.tsx
src/layout/TempLogin.tsx
src/pages/join/JoinPage.tsx

- [Jira Ticket: RL1M-248](https://relay-letter.atlassian.net/browse/RL1M-248)

Refactor: RL1M-248 내 정보 API를 Tanstack-query로 전역 상태로 캐싱

---

src/components/writePage/writeElement/WriteElement.tsx

Fix: height 조정 코드 삭제, 스크롤 상단 고정

---

src/components/writePage/Write.tsx
src/components/writePage/writeElement/WriteElement.tsx

Fix: RL1M-324 height 처리 수정

---

src/components/writePage/writeElement/WriteElement.tsx

Fix: RL1M-324 div 추가

---

src/components/writePage/writeElement/WriteElement.tsx

Fix: RL1M-324 height 100%, 스크롤 위치 수정

---

src/components/writePage/Write.tsx
src/components/writePage/writeElement/WriteElement.tsx

Fix: RL1M-324 스크롤 삭제, 100vh로 변경

---

src/components/writePage/Write.tsx
src/hooks/use100vh.ts

Feat: RL1M-324 uss100vh로 화면 크기 관리

---

src/components/writePage/writeElement/WriteElement.tsx
src/hooks/use100vh.ts

Fix: RL1M-324 use100vh 수정

---

src/components/writePage/Write.tsx
src/components/writePage/writeElement/WriteElement.tsx

Fix: RL1M-324 스크롤 수정

---

src/components/writePage/writeElement/WriteElement.tsx

Fix: RL1M-324 스크롤 재수정 

---

package-lock.json
package.json
src/main.tsx

- [Jira Ticket: RL1M-326](https://relay-letter.atlassian.net/browse/RL1M-326)

Chore: RL1M-326 Hotjar 설치

---

src/components/writePage/Write.tsx
src/components/writePage/writeElement/WriteElement.tsx

Fix: RL1M-324 Header position 수정

---

index.html

- [Jira Ticket: RL1M-327](https://relay-letter.atlassian.net/browse/RL1M-327)

Chore: RL1M-327 Google Tag Manager 설치

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-328](https://relay-letter.atlassian.net/browse/RL1M-328)

Fix: RL1M-328 스크롤 조건 처리, 모바일 체크 후 랜더링

---

src/components/writePage/Write.tsx
src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-329](https://relay-letter.atlassian.net/browse/RL1M-329)
- 타임 아웃 시에도 작성하고 있던 모달이 닫히지 않는 문제를 개선

Fix: RL1M-329 타임아웃 시 작성 모달 닫히도록 개선

---

src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-328](https://relay-letter.atlassian.net/browse/RL1M-328)

[Fix] RL1M-328 pc 화면 깨짐수정, mobilecheck 삭제

---

src/components/writePage/Write.tsx
src/components/writePage/writeElement/WriteElement.tsx

- [Jira Ticket: RL1M-328](https://relay-letter.atlassian.net/browse/RL1M-328)

Fix: RL1M-328 헤더 css 오류 수정

---

src/components/writePage/Write.tsx
src/components/writePage/writeElement/WriteElement.tsx
vite.config.ts

- [Jira Ticket: RL1M-328](https://relay-letter.atlassian.net/browse/RL1M-328)

Fix: RL1M-328 스크롤 제거

---

src/api/queries/letter.ts
src/api/service/LetterService.ts
src/components/InvitePage/Count/Count.tsx
src/components/InvitePage/HostUser.tsx
src/components/InvitePage/Invite.tsx
src/components/InvitePage/Member.tsx
src/components/letterboxPage/Created_Modal.tsx
src/components/letterboxPage/Letter.tsx
src/components/receivePage/ReceiveLetter.tsx
src/components/receivePage/ReceiveLetterContents.tsx
src/components/sharePage/ShareLetter.tsx
src/components/writePage/Write.tsx
src/components/writePage/WriteOrderPopover.tsx
src/components/writePage/writeElement/WriteElement.tsx
src/components/writePage/writeMainModal/WriteMainModal.tsx
vite.config.ts

- [Jira Ticket: RL1M-339](https://relay-letter.atlassian.net/browse/RL1M-339)

Fix: RL1M-339 250526 3차 QA 일부 반영

---

src/components/writePage/Write.tsx
src/components/writePage/writeMainList/WriteOrderList.tsx

- [Jira Ticket: RL1M-351](https://relay-letter.atlassian.net/browse/RL1M-351)

Fix: RL1M-351 위치 아이콘 오류 수정

---

src/components/InvitePage/Count/Count.stories.tsx
src/components/InvitePage/Count/Count.tsx
src/components/InvitePage/HostUser.tsx

- [Jira Ticket: RL1M-355](https://relay-letter.atlassian.net/browse/RL1M-355)
- 인원 수 선택 시 5명일 때만 선택지가 3 이후부터 보이지 않는 문제 수정

Fix: RL1M-355 인원 수 선택 WheelPicker에서 일부 선택지 보이지 않는 문제 수정

---

index.html
src/App.tsx
src/api/config/AccessTokenRepository.ts
src/components/common/Button.tsx
src/components/common/OnlyAuthenticated.tsx
src/components/common/index.ts
src/components/writePage/Write.tsx
src/main.tsx
vite.config.ts

- [Jira Ticket: RL1M-360](https://relay-letter.atlassian.net/browse/RL1M-360)
Etc

Feat: RL1M-360 전역 Auth 체크 컴포넌트 추가
